branch-defaults:
  main:
    environment: staging1
    group_suffix: applecypher
global:
  application_name: applecypher
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.7 running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
